{
   "LIVE":[
      {
         "url":"https://livecdn.fptplay.net/hdevent/vtv3hd_1000.stream/chunklist.m3u8?user_id=null",
         "url1":"http://livecdn.fptplay.net/hdevent/vtv3hd_hls.smil/chunklist_b2500000.m3u8",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Ph\u00e1p",
         "away_team_name":"B\u1ec9",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/doi-tuyen/france-flag-logo.png",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/doi-tuyen/belgium-flag-logo.png",
         "minute":"01:00",
         "country_name":"World Cup 2018",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Flora",
         "away_team_name":"Hapoel Be&#039;er Sheva",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/29116.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/17687.gif",
         "minute":"22:30",
         "country_name":"Champions League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Torpedo Kutaisi",
         "away_team_name":"Sheriff",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/31363.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/17731.gif",
         "minute":"22:30",
         "country_name":"Champions League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Wacker Innsbruck",
         "away_team_name":"Viktoria Plzen",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/29259.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/10184.gif",
         "minute":"22:00",
         "country_name":"Giao h\u1eefu",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Dudelange",
         "away_team_name":"Videoton",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/12798.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/21498.gif",
         "minute":"23:00",
         "country_name":"Champions League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Samtredia",
         "away_team_name":"Tobol",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/VL%20c2/17615.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/VL%20c2/6305.gif",
         "minute":"23:00",
         "country_name":"Europa League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Klaksvik",
         "away_team_name":"Zalgiris",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/VL%20c2/15502.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/VL%20c2/17707.gif",
         "minute":"23:00",
         "country_name":"Europa League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Basel",
         "away_team_name":"Wolverhampton",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/10190.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/10285.gif",
         "minute":"23:00",
         "country_name":"Giao h\u1eefu",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Alashkert",
         "away_team_name":"Celtic",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/21093.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/vl-c1/10844.gif",
         "minute":"23:00",
         "country_name":"Champions League",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Rijeka",
         "away_team_name":"Spartak M",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/17536.gif",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/15118.gif",
         "minute":"23:00",
         "country_name":"Giao h\u1eefu",
         "status":"XEM GI\u1edc"
      },
      {
         "url":"",
         "url1":"",
         "url2":"",
         "url3":"",
         "url4":"",
         "home_team_name":"Croatia",
         "away_team_name":"Anh",
         "home_team_logo":"http://khandaia.com/uploads/team/logo/images/doi-tuyen/croatia-flag-logo.png",
         "away_team_logo":"http://khandaia.com/uploads/team/logo/images/doi-tuyen/england-flag-logo.png",
         "minute":"01:00",
         "country_name":"World Cup 2018",
         "status":"XEM GI\u1edc"
      }
   ]
}
